import pygame

icon=pygame.image.load("icons\\icon.png")
zero=pygame.image.load("icons\\blank.png")
one=pygame.image.load("icons\\1.png")
two=pygame.image.load("icons\\2.png")
three=pygame.image.load("icons\\3.png")
four=pygame.image.load("icons\\4.png")
five=pygame.image.load("icons\\5.png")
six=pygame.image.load("icons\\6.png")
seven=pygame.image.load("icons\\7.png")
eight=pygame.image.load("icons\\8.png")
bomb=pygame.image.load("icons\\bomb.png")
xyzz=pygame.image.load("icons\\xyzzy.png")
flaggedxyzz=pygame.image.load("icons\\flaggedxyzzy.png")
flag=pygame.image.load("icons\\flag.png")
qmark=pygame.image.load("icons\\qmark.png")
default=pygame.image.load("icons\\def.png")
ok=pygame.image.load("icons\\accept.png")
okIn=pygame.image.load("icons\\acceptIn.png")
cat=pygame.image.load("icons\\cat.png")
catWin=pygame.image.load("icons\\catWin.png")
catLose=pygame.image.load("icons\\catLose.png")

numbers=[zero,one,two,three,four,five,six,seven,eight]
